[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Karol Saputa <karol.saputa@gmail.com>"]
readme = "README.md"
packages = [{include = "python_template"}]

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0.1"
python-dotenv = "^1.0.0"
build = "^0.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
